extends: default

ignore: |
   .venv

rules:
  comments-indentation: disable
  document-start: disable
  line-length:
    allow-non-breakable-inline-mappings: true
    allow-non-breakable-words: true
    max: 80
